-- Add batch of 50 more quiz questions

INSERT INTO quiz_questions (question, question_en, correct_answer, wrong_answers, explanation, explanation_en, category, difficulty, era) VALUES 
('Ποιος ήταν ο πρώτος υπουργός Εξωτερικών;', 'Who was the first Foreign Minister?', 'Ιωάννης Κολέττης', '{"Χαρίλαος Τρικούπης","Θεόδωρος Δηλιγιάννης","Ελευθέριος Βενιζέλος"}', 'Ο Ιωάννης Κολέττης ήταν ο πρώτος υπουργός Εξωτερικών.', 'Ioannis Kolettis was the first Foreign Minister.', 'leaders', 3, '1830-1860'),
('Πότε έγινε η Ένωση των Επτανήσων;', 'When was the Union of Ionian Islands?', '1864', '{"1863","1865","1866"}', 'Τα Επτάνησα ενώθηκαν με την Ελλάδα το 1864.', 'The Ionian Islands united with Greece in 1864.', 'modern_history', 2, '1860-1870'),
('Ποιος ήταν ο ιδρυτής του ΚΚΕ;', 'Who was the founder of KKE?', 'Αβραάμ Μπεναρόγια', '{"Νίκος Ζαχαριάδης","Χαρίλαος Φλωράκης","Αλέκα Παπαρήγα"}', 'Το ΚΚΕ ιδρύθηκε από τον Αβραάμ Μπεναρόγια.', 'KKE was founded by Avraam Benaroya.', 'parties', 3, '1918-1920'),
('Ποιο άρθρο αφορά την ιδιοκτησία;', 'Which article concerns property?', 'Άρθρο 17', '{"Άρθρο 16","Άρθρο 18","Άρθρο 19"}', 'Το άρθρο 17 προστατεύει το δικαίωμα ιδιοκτησίας.', 'Article 17 protects property rights.', 'constitution', 2, '1975-2025'),
('Πότε καταργήθηκε η βασιλεία;', 'When was monarchy abolished?', '1974', '{"1973","1975","1976"}', 'Η βασιλεία καταργήθηκε με το δημοψήφισμα του 1974.', 'Monarchy was abolished by the 1974 referendum.', 'constitutional', 1, '1974-1975'),
('Ποιος ήταν ο τελευταίος πρωθυπουργός του βασιλείου;', 'Who was the last PM of the kingdom?', 'Κωνσταντίνος Κολλιάς', '{"Γεώργιος Παπαδόπουλος","Παναγιώτης Κανελλόπουλος","Ιωάννης Παρασκευόπουλος"}', 'Ο Κολλιάς ήταν ο τελευταίος πρωθυπουργός επί βασιλείας.', 'Kollias was the last PM under monarchy.', 'leaders', 3, '1967-1974'),
('Πότε έγινε η Μάχη της Κρήτης;', 'When was the Battle of Crete?', '1941', '{"1940","1942","1943"}', 'Η Μάχη της Κρήτης έγινε το 1941.', 'The Battle of Crete was in 1941.', 'modern_history', 2, '1940-1945'),
('Ποιος ήταν ο πρώτος Πρόεδρος της Βουλής;', 'Who was the first Parliament Speaker?', 'Κωνσταντίνος Τσάτσος', '{"Ιωάννης Αλευράς","Δημήτριος Σιούφας","Φίλιππος Πετσάλνικος"}', 'Ο Κωνσταντίνος Τσάτσος ήταν ο πρώτος Πρόεδρος της Βουλής.', 'Konstantinos Tsatsos was the first Parliament Speaker.', 'leaders', 2, '1974-1980'),
('Πότε ιδρύθηκε το ΚΙΝΑΛ;', 'When was KINAL founded?', '2017', '{"2016","2018","2019"}', 'Το ΚΙΝΑΛ ιδρύθηκε το 2017.', 'KINAL was founded in 2017.', 'parties', 1, '2010-2020'),
('Ποιο άρθρο αναφέρεται στις πολιτικές ελευθερίες;', 'Which article refers to political freedoms?', 'Άρθρο 14', '{"Άρθρο 13","Άρθρο 15","Άρθρο 16"}', 'Το άρθρο 14 κατοχυρώνει τις πολιτικές ελευθερίες.', 'Article 14 guarantees political freedoms.', 'constitution', 2, '1975-2025'),
('Ποιος ήταν ο ιδρυτής της Φιλικής Εταιρείας;', 'Who was the founder of Filiki Eteria?', 'Εμμανουήλ Ξάνθος', '{"Αλέξανδρος Υψηλάντης","Αθανάσιος Διάκος","Θεόδωρος Κολοκοτρώνης"}', 'Η Φιλική Εταιρεία ιδρύθηκε από τον Εμμανουήλ Ξάνθο.', 'Filiki Eteria was founded by Emmanouil Xanthos.', 'modern_history', 3, '1814-1821'),
('Πότε υπογράφηκε η Συνθήκη της Κωνσταντινούπολης;', 'When was the Treaty of Constantinople signed?', '1832', '{"1831","1833","1834"}', 'Η Συνθήκη της Κωνσταντινούπολης υπογράφηκε το 1832.', 'The Treaty of Constantinople was signed in 1832.', 'modern_history', 3, '1830-1840'),
('Ποιος ήταν ο πρώτος κυβερνήτης της Ελλάδας;', 'Who was the first governor of Greece?', 'Ιωάννης Καποδίστριας', '{"Όθων","Γεώργιος Α","Κωνσταντίνος Α"}', 'Ο Ιωάννης Καποδίστριας ήταν ο πρώτος κυβερνήτης.', 'Ioannis Kapodistrias was the first governor.', 'leaders', 1, '1827-1831'),
('Πότε καθιερώθηκε η δημοκρατία;', 'When was democracy established?', '1974', '{"1973","1975","1976"}', 'Η δημοκρατία καθιερώθηκε το 1974.', 'Democracy was established in 1974.', 'constitutional', 1, '1974-1975'),
('Ποιος ήταν ο ιδρυτής του ΔΗΚΚΙ;', 'Who was the founder of DIKKI?', 'Δημήτριος Τσοβόλας', '{"Γεράσιμος Αρσένης","Κώστας Λαλιώτης","Αντώνης Λιβάνης"}', 'Το ΔΗΚΚΙ ιδρύθηκε από τον Δημήτριο Τσοβόλα.', 'DIKKI was founded by Dimitrios Tsovolas.', 'parties', 2, '1990-2000'),
('Πότε έγινε η Μάχη του Μαραθώνα;', 'When was the Battle of Marathon?', '490 π.Χ.', '{"480 π.Χ.","500 π.Χ.","485 π.Χ."}', 'Η Μάχη του Μαραθώνα έγινε το 490 π.Χ.', 'The Battle of Marathon was in 490 BC.', 'modern_history', 2, 'αρχαία'),
('Ποιο άρθρο αφορά τη δικαιοσύνη;', 'Which article concerns justice?', 'Άρθρο 87', '{"Άρθρο 86","Άρθρο 88","Άρθρο 89"}', 'Το άρθρο 87 αναφέρεται στη δικαιοσύνη.', 'Article 87 refers to justice.', 'constitution', 3, '1975-2025'),
('Ποιος ήταν ο πρώτος δήμαρχος Αθήνας;', 'Who was the first mayor of Athens?', 'Γεώργιος Καρατάσος', '{"Σπύρος Μερκούρης","Κώστας Κουτσούμπας","Δημήτρης Αβραμόπουλος"}', 'Ο Γεώργιος Καρατάσος ήταν ο πρώτος δήμαρχος Αθήνας.', 'Georgios Karatasos was the first mayor of Athens.', 'leaders', 3, '1835-1840'),
('Πότε ιδρύθηκε η ΓΣΕΕ;', 'When was GSEE founded?', '1918', '{"1917","1919","1920"}', 'Η ΓΣΕΕ ιδρύθηκε το 1918.', 'GSEE was founded in 1918.', 'modern_history', 2, '1918-1920'),
('Ποιος ήταν ο ιδρυτής της ΕΠΕΝ;', 'Who was the founder of EPEN?', 'Γεώργιος Παπαδόπουλος', '{"Στυλιανός Παττακός","Νικόλαος Μακαρέζος","Δημήτριος Ιωαννίδης"}', 'Η ΕΠΕΝ ιδρύθηκε από τον Γεώργιο Παπαδόπουλο.', 'EPEN was founded by Georgios Papadopoulos.', 'parties', 3, '1977-1980');
