-- Add authentic Greek political history questions with proper translations

INSERT INTO quiz_questions (question, question_en, correct_answer, wrong_answers, explanation, explanation_en, category, difficulty, era) VALUES 
-- Modern History Questions
('Πότε έγινε η Απελευθέρωση της Αθήνας;', 'When was Athens liberated?', '12 Οκτωβρίου 1944', '{"10 Οκτωβρίου 1944","14 Οκτωβρίου 1944","15 Οκτωβρίου 1944"}', 'Η Αθήνα απελευθερώθηκε από τους Γερμανούς στις 12 Οκτωβρίου 1944.', 'Athens was liberated from the Germans on October 12, 1944.', 'modern_history', 2, '1940-1950'),
('Ποιος ήταν ο αρχηγός της ΕΔΕΣ;', 'Who was the leader of EDES?', 'Ναπολέων Ζέρβας', '{"Άρης Βελουχιώτης","Στέφανος Σαράφης","Δημήτριος Ψαρρός"}', 'Η ΕΔΕΣ (Εθνικός Δημοκρατικός Ελληνικός Σύνδεσμος) ιδρύθηκε από τον Ναπολέων Ζέρβα.', 'EDES (National Republican Greek League) was founded by Napoleon Zervas.', 'modern_history', 2, '1940-1950'),
('Πότε τελείωσε η Γερμανική Κατοχή;', 'When did the German Occupation end?', 'Οκτώβριος 1944', '{"Σεπτέμβριος 1944","Νοέμβριος 1944","Δεκέμβριος 1944"}', 'Η Γερμανική Κατοχή τελείωσε τον Οκτώβριο του 1944.', 'The German Occupation ended in October 1944.', 'modern_history', 1, '1940-1950'),
('Ποιος ήταν ο αρχηγός του ΕΚΚΑ;', 'Who was the leader of EKKA?', 'Δημήτριος Ψαρρός', '{"Ναπολέων Ζέρβας","Άρης Βελουχιώτης","Στέφανος Σαράφης"}', 'Ο Δημήτριος Ψαρρός ήταν αρχηγός του ΕΚΚΑ (Εθνική και Κοινωνική Απελευθέρωση).', 'Dimitrios Psarros was the leader of EKKA (National and Social Liberation).', 'modern_history', 3, '1940-1950'),
('Πότε έγινε η Συμφωνία της Βάρκιζας;', 'When was the Varkiza Agreement?', '12 Φεβρουαρίου 1945', '{"10 Φεβρουαρίου 1945","14 Φεβρουαρίου 1945","15 Φεβρουαρίου 1945"}', 'Η Συμφωνία της Βάρκιζας υπογράφηκε στις 12 Φεβρουαρίου 1945.', 'The Varkiza Agreement was signed on February 12, 1945.', 'modern_history', 3, '1940-1950'),

-- Political Parties Questions  
('Πότε ιδρύθηκε η Εθνική Ριζοσπαστική Ένωση;', 'When was the National Radical Union founded?', '1956', '{"1955","1957","1958"}', 'Η ΕΡΕ ιδρύθηκε το 1956 από τον Κωνσταντίνο Καραμανλή.', 'ERE was founded in 1956 by Constantine Karamanlis.', 'parties', 2, '1950-1960'),
('Ποιος ήταν ο ιδρυτής του Προοδευτικού Κόμματος;', 'Who was the founder of the Progressive Party?', 'Σπύρος Μαρκεζίνης', '{"Παναγιώτης Κανελλόπουλος","Στέφανος Στεφανόπουλος","Ευάγγελος Αβέρωφ"}', 'Το Προοδευτικό Κόμμα ιδρύθηκε από τον Σπύρο Μαρκεζίνη το 1955.', 'The Progressive Party was founded by Spyros Markezinis in 1955.', 'parties', 2, '1950-1960'),
('Πότε διαλύθηκε η ΕΔΑ;', 'When was EDA dissolved?', '1967', '{"1966","1968","1969"}', 'Η ΕΔΑ (Ενιαία Δημοκρατική Αριστερά) διαλύθηκε από τη χούντα το 1967.', 'EDA (United Democratic Left) was dissolved by the junta in 1967.', 'parties', 2, '1960-1970'),
('Ποιος ήταν ο πρώτος γραμματέας του ΠΑΣΟΚ;', 'Who was the first secretary of PASOK?', 'Ανδρέας Παπανδρέου', '{"Κώστας Σημίτης","Γιώργος Παπανδρέου","Ευάγγελος Βενιζέλος"}', 'Ο Ανδρέας Παπανδρέου ήταν ο ιδρυτής και πρώτος πρόεδρος του ΠΑΣΟΚ.', 'Andreas Papandreou was the founder and first president of PASOK.', 'parties', 1, '1974-1980'),
('Πότε ιδρύθηκε το ΚΚΕ εσωτερικού;', 'When was KKE Interior founded?', '1968', '{"1967","1969","1970"}', 'Το ΚΚΕ εσωτερικού ιδρύθηκε το 1968 ως αποτέλεσμα του σχίσματος στο ΚΚΕ.', 'KKE Interior was founded in 1968 as a result of the KKE schism.', 'parties', 3, '1960-1970'),

-- Constitutional Questions
('Πόσα άρθρα είχε το Σύνταγμα του 1952;', 'How many articles had the 1952 Constitution?', '114', '{"110","118","120"}', 'Το Σύνταγμα του 1952 είχε 114 άρθρα.', 'The 1952 Constitution had 114 articles.', 'constitution', 3, '1950-1960'),
('Ποιο άρθρο του Συντάγματος αναφέρεται στην Ορθόδοξη Εκκλησία;', 'Which article of the Constitution refers to the Orthodox Church?', 'Άρθρο 3', '{"Άρθρο 2","Άρθρο 4","Άρθρο 5"}', 'Το άρθρο 3 του Συντάγματος αναφέρεται στην επικρατούσα θρησκεία.', 'Article 3 of the Constitution refers to the prevailing religion.', 'constitution', 2, '1975-2025'),
('Πότε ψηφίστηκε το Σύνταγμα του 1968;', 'When was the 1968 Constitution voted?', '29 Σεπτεμβρίου 1968', '{"28 Σεπτεμβρίου 1968","30 Σεπτεμβρίου 1968","1 Οκτωβρίου 1968"}', 'Το Σύνταγμα της χούντας ψηφίστηκε στις 29 Σεπτεμβρίου 1968.', 'The junta Constitution was voted on September 29, 1968.', 'constitution', 3, '1967-1974'),
('Ποιο άρθρο καθορίζει τη θητεία της Βουλής;', 'Which article determines the term of Parliament?', 'Άρθρο 53', '{"Άρθρο 52","Άρθρο 54","Άρθρο 55"}', 'Το άρθρο 53 καθορίζει ότι η θητεία της Βουλής είναι τετραετής.', 'Article 53 determines that the term of Parliament is four years.', 'constitution', 2, '1975-2025'),
('Πότε καταργήθηκε η θανατική ποινή;', 'When was the death penalty abolished?', '2004', '{"2003","2005","2006"}', 'Η θανατική ποινή καταργήθηκε πλήρως το 2004.', 'The death penalty was completely abolished in 2004.', 'constitution', 2, '2000-2010');
