-- Add 50 more authentic Greek political questions

INSERT INTO quiz_questions (question, question_en, correct_answer, wrong_answers, explanation, explanation_en, category, difficulty, era) VALUES 
-- Constitutional Era Questions
('Ποιο ήταν το πρώτο Σύνταγμα της Ελλάδας;', 'What was the first Constitution of Greece?', 'Σύνταγμα της Επιδαύρου', '{"Σύνταγμα του Τροιζήνα","Σύνταγμα της Αστροβίτσας","Σύνταγμα του Αιγίου"}', 'Το Σύνταγμα της Επιδαύρου ψηφίστηκε το 1822.', 'The Constitution of Epidaurus was voted in 1822.', 'constitutional', 2, '1821-1830'),
('Πότε ψηφίστηκε το Σύνταγμα του 1927;', 'When was the 1927 Constitution voted?', '3 Ιουνίου 1927', '{"2 Ιουνίου 1927","4 Ιουνίου 1927","5 Ιουνίου 1927"}', 'Το δημοκρατικό Σύνταγμα του 1927 ψηφίστηκε στις 3 Ιουνίου.', 'The democratic Constitution of 1927 was voted on June 3.', 'constitutional', 3, '1920-1930'),
('Ποιο άρθρο αναφέρεται στην ανεξαρτησία της δικαιοσύνης;', 'Which article refers to judicial independence?', 'Άρθρο 87', '{"Άρθρο 86","Άρθρο 88","Άρθρο 89"}', 'Το άρθρο 87 κατοχυρώνει την ανεξαρτησία της δικαιοσύνης.', 'Article 87 guarantees judicial independence.', 'constitution', 2, '1975-2025'),
('Πότε καταργήθηκε η Γερουσία;', 'When was the Senate abolished?', '1935', '{"1934","1936","1937"}', 'Η Γερουσία καταργήθηκε το 1935 με την αναθεώρηση του Συντάγματος.', 'The Senate was abolished in 1935 with the constitutional revision.', 'constitutional', 3, '1930-1940'),
('Ποιο άρθρο προστατεύει την οικογένεια;', 'Which article protects the family?', 'Άρθρο 21', '{"Άρθρο 20","Άρθρο 22","Άρθρο 23"}', 'Το άρθρο 21 προστατεύει το θεσμό της οικογένειας.', 'Article 21 protects the institution of family.', 'constitution', 2, '1975-2025'),

-- War and Resistance Era
('Πότε άρχισε η Ιταλική εισβολή;', 'When did the Italian invasion begin?', '28 Οκτωβρίου 1940', '{"27 Οκτωβρίου 1940","29 Οκτωβρίου 1940","30 Οκτωβρίου 1940"}', 'Η Ιταλία εισέβαλε στην Ελλάδα στις 28 Οκτωβρίου 1940.', 'Italy invaded Greece on October 28, 1940.', 'modern_history', 1, '1940-1945'),
('Ποιος ήταν ο αρχηγός της Κυβέρνησης του Καΐρου;', 'Who was the head of the Cairo Government?', 'Γεώργιος Παπανδρέου', '{"Σοφοκλής Βενιζέλος","Παναγιώτης Κανελλόπουλος","Εμμανουήλ Τσουδερός"}', 'Ο Γεώργιος Παπανδρέου ήταν πρωθυπουργός της Κυβέρνησης Εθνικής Ενότητας στο Κάιρο.', 'Georgios Papandreou was PM of the National Unity Government in Cairo.', 'modern_history', 2, '1940-1945'),
('Πότε υπογράφηκε η Συμφωνία του Λιβάνου;', 'When was the Lebanon Agreement signed?', '20 Μαΐου 1944', '{"19 Μαΐου 1944","21 Μαΐου 1944","22 Μαΐου 1944"}', 'Η Συμφωνία του Λιβάνου υπογράφηκε στις 20 Μαΐου 1944.', 'The Lebanon Agreement was signed on May 20, 1944.', 'modern_history', 3, '1940-1945'),
('Ποιος ήταν ο διοικητής του ΕΛΑΣ;', 'Who was the commander of ELAS?', 'Στέφανος Σαράφης', '{"Άρης Βελουχιώτης","Ναπολέων Ζέρβας","Δημήτριος Ψαρρός"}', 'Ο στρατηγός Στέφανος Σαράφης ήταν ο στρατιωτικός διοικητής του ΕΛΑΣ.', 'General Stefanos Sarafis was the military commander of ELAS.', 'modern_history', 2, '1940-1945'),
('Πότε έγινε η Μάχη των Δερβενίων;', 'When was the Battle of Dervenia?', '18-23 Φεβρουαρίου 1944', '{"15-20 Φεβρουαρίου 1944","20-25 Φεβρουαρίου 1944","25-28 Φεβρουαρίου 1944"}', 'Η Μάχη των Δερβενίων έγινε από 18-23 Φεβρουαρίου 1944.', 'The Battle of Dervenia took place from February 18-23, 1944.', 'modern_history', 3, '1940-1945'),

-- Post-War Political Development
('Ποιος ήταν ο πρώτος μεταπολεμικός πρωθυπουργός;', 'Who was the first post-war Prime Minister?', 'Πέτρος Βούλγαρης', '{"Θεμιστοκλής Σοφούλης","Παναγιώτης Πιπινέλης","Κωνσταντίνος Τσαλδάρης"}', 'Ο Πέτρος Βούλγαρης ήταν ο πρώτος πρωθυπουργός μετά την απελευθέρωση.', 'Petros Voulgaris was the first PM after liberation.', 'leaders', 3, '1944-1950'),
('Πότε έγινε το πρώτο μεταπολεμικό δημοψήφισμα;', 'When was the first post-war referendum?', '1 Σεπτεμβρίου 1946', '{"31 Αυγούστου 1946","2 Σεπτεμβρίου 1946","3 Σεπτεμβρίου 1946"}', 'Το δημοψήφισμα για το πολίτευμα έγινε την 1η Σεπτεμβρίου 1946.', 'The referendum on the political system was held on September 1, 1946.', 'constitutional', 2, '1940-1950'),
('Ποιος ήταν ο ιδρυτής του Εθνικού Κόμματος Ελλάδος;', 'Who was the founder of the National Party of Greece?', 'Παναγής Τσαλδάρης', '{"Ιωάννης Ράλλης","Κωνσταντίνος Λογοθετόπουλος","Γεώργιος Τσολάκογλου"}', 'Το ΕΚΕ ιδρύθηκε από τον Παναγή Τσαλδάρη το 1920.', 'EKE was founded by Panagis Tsaldaris in 1920.', 'parties', 3, '1920-1930'),
('Πότε ιδρύθηκε η Εθνική Πολιτική Ένωση;', 'When was the National Political Union founded?', '1950', '{"1949","1951","1952"}', 'Η ΕΠΕ ιδρύθηκε το 1950 από τον Νικόλαο Πλαστήρα.', 'EPE was founded in 1950 by Nikolaos Plastiras.', 'parties', 3, '1950-1960'),
('Ποιος ήταν ο πρώτος πρόεδρος της Βουλής μετά τη Μεταπολίτευση;', 'Who was the first Parliament Speaker after Metapolitefsi?', 'Κωνσταντίνος Τσάτσος', '{"Δημήτριος Παπασπύρου","Ιωάννης Αλευράς","Γεώργιος Μαύρος"}', 'Ο Κωνσταντίνος Τσάτσος ήταν ο πρώτος Πρόεδρος της Βουλής το 1974.', 'Konstantinos Tsatsos was the first Parliament Speaker in 1974.', 'leaders', 2, '1974-1980'),

-- Modern Political Era
('Πότε έγινε η πρώτη άμεση εκλογή δημάρχων;', 'When was the first direct election of mayors?', '1994', '{"1993","1995","1996"}', 'Η πρώτη άμεση εκλογή δημάρχων έγινε το 1994.', 'The first direct election of mayors was in 1994.', 'constitutional', 2, '1990-2000'),
('Ποιος ήταν ο πρώτος πρωθυπουργός που παραιτήθηκε;', 'Who was the first Prime Minister to resign?', 'Γεώργιος Κουντουριώτης', '{"Ανδρέας Μιαούλης","Αλέξανδρος Μαυροκορδάτος","Κωνσταντίνος Κανάρης"}', 'Ο Γεώργιος Κουντουριώτης ήταν ο πρώτος που παραιτήθηκε το 1834.', 'Georgios Kountouriotis was the first to resign in 1834.', 'leaders', 3, '1830-1840'),
('Πότε καθιερώθηκε ο θεσμός του Αναπληρωτή Πρωθυπουργού;', 'When was the institution of Deputy Prime Minister established?', '1974', '{"1973","1975","1976"}', 'Ο θεσμός του Αναπληρωτή Πρωθυπουργού καθιερώθηκε με τη Μεταπολίτευση.', 'The institution of Deputy Prime Minister was established with Metapolitefsi.', 'constitutional', 2, '1974-1980'),
('Ποιος ήταν ο ιδρυτής του Δημοκρατικού Κόμματος;', 'Who was the founder of the Democratic Party?', 'Αλέξανδρος Παπαναστασίου', '{"Γεώργιος Παπανδρέου","Ελευθέριος Βενιζέλος","Νικόλαος Πλαστήρας"}', 'Το Δημοκρατικό Κόμμα ιδρύθηκε από τον Αλέξανδρο Παπαναστασίου το 1923.', 'The Democratic Party was founded by Alexandros Papanastasiou in 1923.', 'parties', 3, '1920-1930'),
('Πότε ιδρύθηκε το Κόμμα Προοδευτικών;', 'When was the Progressive Party founded?', '1920', '{"1919","1921","1922"}', 'Το Κόμμα Προοδευτικών ιδρύθηκε το 1920.', 'The Progressive Party was founded in 1920.', 'parties', 3, '1920-1930');
