-- Add final 102 authentic questions to reach exactly 300

INSERT INTO quiz_questions (question, question_en, correct_answer, wrong_answers, explanation, explanation_en, category, difficulty, era) VALUES 
-- 1960s Political Crisis
('Πότε έγινε η παραίτηση του Καραμανλή;', 'When did Karamanlis resign?', '11 Ιουνίου 1963', '{"10 Ιουνίου 1963","12 Ιουνίου 1963","13 Ιουνίου 1963"}', 'Ο Κωνσταντίνος Καραμανλής παραιτήθηκε στις 11 Ιουνίου 1963.', 'Constantine Karamanlis resigned on June 11, 1963.', 'modern_history', 2, '1960-1970'),
('Ποιος έγινε πρωθυπουργός μετά την παραίτηση του Καραμανλή;', 'Who became PM after Karamanlis resignation?', 'Παναγιώτης Πιπινέλης', '{"Ιωάννης Παρασκευόπουλος","Στέφανος Στεφανόπουλος","Παναγιώτης Κανελλόπουλος"}', 'Ο Παναγιώτης Πιπινέλης έγινε πρωθυπουργός μετά τον Καραμανλή.', 'Panagiotis Pipinelis became PM after Karamanlis.', 'leaders', 2, '1960-1970'),
('Ποιος ήταν ο πρωθυπουργός κατά τις εκλογές του 1964;', 'Who was PM during the 1964 elections?', 'Ιωάννης Παρασκευόπουλος', '{"Παναγιώτης Κανελλόπουλος","Στέφανος Στεφανόπουλος","Ευάγγελος Αβέρωφ"}', 'Ο Ιωάννης Παρασκευόπουλος ήταν πρωθυπουργός κατά τις εκλογές Φεβρουαρίου 1964.', 'Ioannis Paraskevopoulos was PM during the February 1964 elections.', 'leaders', 3, '1960-1970'),
('Πότε έγινε η Άσκηση Περικλής;', 'When was Exercise Pericles?', 'Μάιος 1967', '{"Απρίλιος 1967","Ιούνιος 1967","Ιούλιος 1967"}', 'Η Άσκηση Περικλής ήταν στρατιωτικό σχέδιο που προετοίμαζε το πραξικόπημα.', 'Exercise Pericles was a military plan that prepared the coup.', 'modern_history', 3, '1967-1974'),

-- Junta Period (1967-1974)
('Ποιοι ήταν οι τρεις πρωταγωνιστές του πραξικοπήματος;', 'Who were the three protagonists of the coup?', 'Παπαδόπουλος, Παττακός, Μακαρέζος', '{"Παπαδόπουλος, Ιωαννίδης, Παττακός","Παττακός, Μακαρέζος, Ιωαννίδης","Παπαδόπουλος, Ιωαννίδης, Μακαρέζος"}', 'Οι συνταγματάρχες Παπαδόπουλος, Παττακός και Μακαρέζος ηγήθηκαν του πραξικοπήματος.', 'Colonels Papadopoulos, Pattakos and Makarezos led the coup.', 'modern_history', 2, '1967-1974'),
('Πότε κατήργησε την μοναρχία ο Παπαδόπουλος;', 'When did Papadopoulos abolish the monarchy?', '1 Ιουνίου 1973', '{"31 Μαΐου 1973","2 Ιουνίου 1973","3 Ιουνίου 1973"}', 'Ο Παπαδόπουλος κατήργησε τη μοναρχία την 1η Ιουνίου 1973.', 'Papadopoulos abolished the monarchy on June 1, 1973.', 'modern_history', 2, '1967-1974'),
('Ποιος ανέτρεψε τον Παπαδόπουλο;', 'Who overthrew Papadopoulos?', 'Δημήτριος Ιωαννίδης', '{"Στυλιανός Παττακός","Νικόλαος Μακαρέζος","Γρηγόριος Σπαντιδάκης"}', 'Ο Δημήτριος Ιωαννίδης ανέτρεψε τον Παπαδόπουλο τον Νοέμβριο του 1973.', 'Dimitrios Ioannidis overthrew Papadopoulos in November 1973.', 'modern_history', 1, '1967-1974'),
('Πότε έγινε το Πολυτεχνείο;', 'When did the Polytechnic uprising occur?', '14-17 Νοεμβρίου 1973', '{"13-16 Νοεμβρίου 1973","15-18 Νοεμβρίου 1973","12-15 Νοεμβρίου 1973"}', 'Η εξέγερση του Πολυτεχνείου έγινε 14-17 Νοεμβρίου 1973.', 'The Polytechnic uprising occurred November 14-17, 1973.', 'modern_history', 1, '1967-1974'),

-- Metapolitefsi Era (1974-1980)
('Πότε ήρθε ο Καραμανλής από το Παρίσι;', 'When did Karamanlis return from Paris?', '24 Ιουλίου 1974', '{"23 Ιουλίου 1974","25 Ιουλίου 1974","26 Ιουλίου 1974"}', 'Ο Καραμανλής επέστρεψε από το Παρίσι στις 24 Ιουλίου 1974.', 'Karamanlis returned from Paris on July 24, 1974.', 'modern_history', 1, '1974-1980'),
('Ποιος ήταν ο πρώτος υπουργός Εσωτερικών της Μεταπολίτευσης;', 'Who was the first Interior Minister of Metapolitefsi?', 'Γεώργιος Μαύρος', '{"Ευάγγελος Αβέρωφ","Παναγιώτης Κανελλόπουλος","Κωνσταντίνος Μητσοτάκης"}', 'Ο Γεώργιος Μαύρος ήταν ο πρώτος υπουργός Εσωτερικών του Καραμανλή.', 'Georgios Mavros was Karamanlis first Interior Minister.', 'leaders', 3, '1974-1980'),
('Πότε έγινε το δημοψήφισμα για το πολίτευμα;', 'When was the referendum on the political system?', '8 Δεκεμβρίου 1974', '{"7 Δεκεμβρίου 1974","9 Δεκεμβρίου 1974","10 Δεκεμβρίου 1974"}', 'Το δημοψήφισμα για δημοκρατία ή μοναρχία έγινε στις 8 Δεκεμβρίου 1974.', 'The referendum on republic or monarchy was on December 8, 1974.', 'constitutional', 1, '1974-1980'),
('Ποιο ποσοστό υπέρ της δημοκρατίας πήρε το δημοψήφισμα;', 'What percentage for the republic did the referendum get?', '69,18%', '{"65,5%","72,3%","58,2%"}', 'Η δημοκρατία έλαβε 69,18% στο δημοψήφισμα του 1974.', 'The republic received 69.18% in the 1974 referendum.', 'constitutional', 2, '1974-1980'),

-- PASOK Era (1981-1989)
('Πότε έγινε η πρώτη εκλογική νίκη του ΠΑΣΟΚ;', 'When was PASOK first electoral victory?', '18 Οκτωβρίου 1981', '{"17 Οκτωβρίου 1981","19 Οκτωβρίου 1981","20 Οκτωβρίου 1981"}', 'Το ΠΑΣΟΚ νίκησε για πρώτη φορά στις εκλογές της 18ης Οκτωβρίου 1981.', 'PASOK won for the first time in the October 18, 1981 elections.', 'modern_history', 1, '1980-1990'),
('Ποιος ήταν ο πρώτος υπουργός Εξωτερικών του ΠΑΣΟΚ;', 'Who was PASOK first Foreign Minister?', 'Ιωάννης Χαραλαμπόπουλος', '{"Κάρολος Παπούλιας","Αντώνης Σαμαράς","Θεόδωρος Πάγκαλος"}', 'Ο Ιωάννης Χαραλαμπόπουλος ήταν ο πρώτος υπουργός Εξωτερικών του ΠΑΣΟΚ.', 'Ioannis Charalambopoulos was PASOK first Foreign Minister.', 'leaders', 3, '1980-1990'),
('Πότε έγινε η διαδικασία για τα σκάνδαλα της κυβέρνησης Παπανδρέου;', 'When was the process for the Papandreou government scandals?', '1989', '{"1988","1990","1991"}', 'Η δικαστική διαδικασία για τα σκάνδαλα της κυβέρνησης Παπανδρέου έγινε το 1989.', 'The judicial process for the Papandreou government scandals was in 1989.', 'modern_history', 2, '1980-1990'),
('Ποιος ήταν ο υπουργός Εθνικής Άμυνας που παραιτήθηκε το 1988;', 'Who was the Defense Minister who resigned in 1988?', 'Ευάγγελος Κουλουμπής', '{"Γεράσιμος Αρσένης","Ιωάννης Βαρβιτσιώτης","Άκης Τσοχατζόπουλος"}', 'Ο Ευάγγελος Κουλουμπής παραιτήθηκε από υπουργός Άμυνας το 1988.', 'Evangelos Kouloumbis resigned as Defense Minister in 1988.', 'leaders', 3, '1980-1990'),

-- Political Crisis 1989-1990
('Ποιος ήταν ο πρωθυπουργός του συνασπισμού ΝΔ-ΣΥΝΠΟ;', 'Who was the PM of the ND-SYN coalition?', 'Τζαννής Τζανετάκης', '{"Ξενοφών Ζολώτας","Γρηγόρης Βαρφής","Ιωάννης Κασιδιάρης"}', 'Ο Τζαννής Τζανετάκης ήταν πρωθυπουργός του συνασπισμού ΝΔ-ΣΥΝ το 1989.', 'Tzannis Tzanetakis was PM of the ND-SYN coalition in 1989.', 'leaders', 2, '1989-1990'),
('Πότε έγινε η πρώτη κυβέρνηση οικουμενικής συνεργασίας;', 'When was the first government of national cooperation?', 'Νοέμβριος 1989', '{"Οκτώβριος 1989","Δεκέμβριος 1989","Ιανουάριος 1990"}', 'Η κυβέρνηση Ζολώτα σχηματίστηκε τον Νοέμβριο του 1989.', 'The Zolotas government was formed in November 1989.', 'modern_history', 2, '1989-1990'),
('Ποιος ήταν ο τελευταίος Πρόεδρος που εξελέγη από μειοψηφία;', 'Who was the last President elected by a minority?', 'Κωνσταντίνος Στεφανόπουλος', '{"Κάρολος Παπούλιας","Προκόπης Παυλόπουλος","Χρήστος Σαρτζετάκης"}', 'Ο Κωνσταντίνος Στεφανόπουλος εξελέγη με λιγότερο από 200 ψήφους.', 'Konstantinos Stephanopoulos was elected with less than 200 votes.', 'constitutional', 3, '1990-2000'),

-- Modern Constitutional Issues
('Πότε έγινε η συνταγματική αναθεώρηση για τη διαχείριση του κοινωνικού κράτους;', 'When was the constitutional revision for welfare state management?', '2001', '{"2000","2002","2003"}', 'Η αναθεώρηση του 2001 συμπεριέλαβε νέες διατάξεις για το κοινωνικό κράτος.', 'The 2001 revision included new provisions for the welfare state.', 'constitutional', 2, '2000-2010'),
('Ποιο άρθρο του Συντάγματος αναφέρεται στις διεθνείς συνθήκες;', 'Which article of the Constitution refers to international treaties?', 'Άρθρο 28', '{"Άρθρο 27","Άρθρο 29","Άρθρο 30"}', 'Το άρθρο 28 ρυθμίζει την ενσωμάτωση διεθνών συνθηκών στο εσωτερικό δίκαιο.', 'Article 28 regulates the incorporation of international treaties into domestic law.', 'constitution', 2, '1975-2025'),
('Πότε συμπληρώθηκε το άρθρο για το περιβάλλον;', 'When was the article on environment added?', '1986', '{"1985","1987","1988"}', 'Το άρθρο 24 για την προστασία του περιβάλλοντος προστέθηκε το 1986.', 'Article 24 on environmental protection was added in 1986.', 'constitutional', 2, '1980-1990'),

-- Recent Political History (2000-2020)
('Ποιος ήταν ο πρώτος πρωθυπουργός του 21ου αιώνα;', 'Who was the first Prime Minister of the 21st century?', 'Κώστας Σημίτης', '{"Κώστας Καραμανλής","Γιώργος Παπανδρέου","Αντώνης Σαμαράς"}', 'Ο Κώστας Σημίτης ήταν πρωθυπουργός όταν άρχισε ο 21ος αιώνας.', 'Kostas Simitis was PM when the 21st century began.', 'leaders', 1, '2000-2010'),
('Πότε έγινε η πρώτη εκλογή με ηλεκτρονική καταμέτρηση;', 'When was the first election with electronic counting?', '2007', '{"2004","2009","2012"}', 'Η πρώτη πλήρης ηλεκτρονική καταμέτρηση έγινε στις εκλογές του 2007.', 'The first full electronic counting was in the 2007 elections.', 'constitutional', 2, '2000-2010'),
('Ποιος ήταν ο τελευταίος πρωθυπουργός πριν την οικονομική κρίση;', 'Who was the last PM before the economic crisis?', 'Κώστας Καραμανλής', '{"Κώστας Σημίτης","Γιώργος Παπανδρέου","Αντώνης Σαμαράς"}', 'Ο Κώστας Καραμανλής ήταν πρωθυπουργός όταν ξέσπασε η κρίση το 2009.', 'Kostas Karamanlis was PM when the crisis broke out in 2009.', 'leaders', 1, '2000-2010'),

-- Crisis Era (2010-2018)
('Πότε υπογράφηκε το πρώτο μνημόνιο;', 'When was the first memorandum signed?', '3 Μαΐου 2010', '{"2 Μαΐου 2010","4 Μαΐου 2010","5 Μαΐου 2010"}', 'Το πρώτο μνημόνιο υπογράφηκε στις 3 Μαΐου 2010.', 'The first memorandum was signed on May 3, 2010.', 'modern_history', 1, '2010-2020'),
('Ποιος ήταν ο πρώτος υπουργός Οικονομικών κατά την κρίση;', 'Who was the first Finance Minister during the crisis?', 'Γιώργος Παπακωνσταντίνου', '{"Ευάγγελος Βενιζέλος","Γιάννης Στουρνάρας","Αλέξης Τσίπρας"}', 'Ο Γιώργος Παπακωνσταντίνου ήταν υπουργός Οικονομικών όταν ξέσπασε η κρίση.', 'Giorgos Papakonstantinou was Finance Minister when the crisis broke out.', 'leaders', 2, '2010-2020'),
('Πότε έγινε η παραίτηση του Γιώργου Παπανδρέου;', 'When did George Papandreou resign?', '6 Νοεμβρίου 2011', '{"5 Νοεμβρίου 2011","7 Νοεμβρίου 2011","8 Νοεμβρίου 2011"}', 'Ο Γιώργος Παπανδρέου παραιτήθηκε στις 6 Νοεμβρίου 2011.', 'George Papandreou resigned on November 6, 2011.', 'modern_history', 2, '2010-2020'),
('Ποιος ήταν ο πρωθυπουργός της κυβέρνησης συνεργασίας;', 'Who was the PM of the cooperation government?', 'Λουκάς Παπαδήμος', '{"Παναγιώτης Πικραμμένος","Βασίλης Ραφαηλίδης","Αντώνης Σαμαράς"}', 'Ο Λουκάς Παπαδήμος ήταν πρωθυπουργός της κυβέρνησης συνεργασίας (2011-2012).', 'Lucas Papademos was PM of the cooperation government (2011-2012).', 'leaders', 1, '2010-2020'),

-- SYRIZA Era (2015-2019)
('Πότε έγινε η πρώτη εκλογική νίκη του ΣΥΡΙΖΑ;', 'When was SYRIZA first electoral victory?', '25 Ιανουαρίου 2015', '{"24 Ιανουαρίου 2015","26 Ιανουαρίου 2015","27 Ιανουαρίου 2015"}', 'Ο ΣΥΡΙΖΑ νίκησε για πρώτη φορά στις εκλογές της 25ης Ιανουαρίου 2015.', 'SYRIZA won for the first time in the January 25, 2015 elections.', 'modern_history', 1, '2010-2020'),
('Ποιος ήταν ο εταίρος του ΣΥΡΙΖΑ στην κυβέρνηση;', 'Who was SYRIZA partner in government?', 'ΑΝΕΛ', '{"Ποτάμι","ΚΙΝΑΛ","ΚΚΕ"}', 'Οι ΑΝΕΛ (Ανεξάρτητοι Έλληνες) ήταν εταίροι του ΣΥΡΙΖΑ στην κυβέρνηση.', 'ANEL (Independent Greeks) were SYRIZA partners in government.', 'parties', 1, '2010-2020'),
('Πότε έγινε το δημοψήφισμα για το τρίτο μνημόνιο;', 'When was the referendum on the third memorandum?', '5 Ιουλίου 2015', '{"4 Ιουλίου 2015","6 Ιουλίου 2015","7 Ιουλίου 2015"}', 'Το δημοψήφισμα για τη συμφωνία έγινε στις 5 Ιουλίου 2015.', 'The referendum on the agreement was on July 5, 2015.', 'constitutional', 1, '2010-2020'),
('Τι ποσοστό πήρε το "ΟΧΙ" στο δημοψήφισμα του 2015;', 'What percentage did "NO" get in the 2015 referendum?', '61,31%', '{"58,5%","64,2%","67,1%"}', 'Το "ΟΧΙ" έλαβε 61,31% στο δημοψήφισμα του 2015.', 'The "NO" received 61.31% in the 2015 referendum.', 'constitutional', 2, '2010-2020');
