-- Complete the remaining scenarios 13-35 with proper matching

-- Scenario 13: Στρατιωτική Κρίση (Military Crisis)
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(13, 'Πλήρης στρατιωτική κινητοποίηση και αμυντική στάση', 'Full military mobilization and defensive stance', 8, -4, 2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 3, "ΚΚΕ": 2, "ΕΛ": 4}', 'Ισχυρή αποτροπή αλλά τεράστιο οικονομικό κόστος.', 'Strong deterrence but huge economic cost.'),
(13, 'Διπλωματική επίλυση με διεθνή διαμεσολάβηση', 'Diplomatic resolution with international mediation', 5, -1, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 2}', 'Ειρηνική επίλυση αλλά πιθανές εδαφικές παραχωρήσεις.', 'Peaceful resolution but possible territorial concessions.'),
(13, 'Στρατηγική αποχώρηση και επανεξοπλισμός', 'Strategic withdrawal and rearmament', 6, -2, 1, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 2, "ΚΚΕ": 3, "ΕΛ": 1}', 'Αποφυγή σύγκρουσης αλλά απώλεια κύρους.', 'Conflict avoidance but prestige loss.');

-- Scenario 14: Κυβερνοεπίθεση (Cyber Attack)
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(14, 'Άμεση αποσύνδεση συστημάτων και κήρυξη κυβερνοπολέμου', 'Immediate system disconnection and cyber war declaration', 7, -3, 1, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 2, "ΕΛ": 4}', 'Προστασία συστημάτων αλλά παράλυση υπηρεσιών.', 'System protection but service paralysis.'),
(14, 'Διεθνή συνεργασία και κοινή αντίδραση με συμμάχους', 'International cooperation and joint response with allies', 4, -1, 2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Αποτελεσματική αντιμετώπιση με διεθνή στήριξη.', 'Effective response with international support.'),
(14, 'Αθόρυβη αποκατάσταση και ενίσχυση κυβερνοάμυνας', 'Silent restoration and cyber defense strengthening', 3, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 3, "ΚΚΕ": 3, "ΕΛ": 2}', 'Αποφυγή πανικού αλλά κίνδυνος επανάληψης.', 'Panic avoidance but repetition risk.');

-- Add 3 options each for scenarios 15-35 using a loop approach
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(15, 'Κλείσιμο συνόρων και επιστροφή μεταναστών', 'Border closure and migrant returns', 8, -1, -3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 1, "ΠΑΣΟΚ": 2, "ΚΚΕ": 2, "ΕΛ": 4}', 'Μείωση εισροών αλλά διεθνής καταδίκη.', 'Reduced inflows but international condemnation.'),
(15, 'Ευρωπαϊκή λύση και αναδιανομή μεταναστών', 'European solution and migrant redistribution', 5, -2, 4, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 2}', 'Διεθνής στήριξη αλλά αργή υλοποίηση.', 'International support but slow implementation.'),
(15, 'Ενταξιακά προγράμματα και στήριξη νησιών', 'Integration programs and island support', 6, -3, 3, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 2}', 'Ανθρωπιστική προσέγγιση αλλά υψηλό κόστος.', 'Humanitarian approach but high cost.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(16, 'Κρατικοποίηση ενεργειακών εταιρειών', 'Nationalization of energy companies', 9, -3, 2, '{"ΝΔ": 1, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 3, "ΚΚΕ": 4, "ΕΛ": 3}', 'Κρατικός έλεγχος αλλά διεθνής καταδίκη.', 'State control but international condemnation.'),
(16, 'Διαφοροποίηση προμηθευτών και ΑΠΕ', 'Supplier diversification and renewables', 5, -2, 3, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Μακροπρόθεσμη ενεργειακή ανεξαρτησία.', 'Long-term energy independence.'),
(16, 'Συνεργασία με παραδοσιακούς προμηθευτές', 'Cooperation with traditional suppliers', 7, 1, -2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 4}', 'Άμεση λύση αλλά εξάρτηση.', 'Immediate solution but dependence.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(17, 'Μαζικές προσλήψεις γιατρών και νοσηλευτών', 'Mass hiring of doctors and nurses', 4, -4, 4, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Βελτίωση υπηρεσιών υγείας αλλά μεγάλο κόστος.', 'Healthcare service improvement but large cost.'),
(17, 'Ιδιωτικοποίηση νοσοκομείων και συμπράξεις', 'Hospital privatization and partnerships', 8, 2, -3, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 1, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτικότητα αλλά αύξηση κόστους για πολίτες.', 'Efficiency but increased costs for citizens.'),
(17, 'Στοχευμένη ενίσχυση και αναδιοργάνωση ΕΣΥ', 'Targeted reinforcement and NHS reorganization', 5, -2, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Σταδιακή βελτίωση με ισορροπημένο κόστος.', 'Gradual improvement with balanced cost.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(18, 'Άμεση συμφωνία με εκπαιδευτικούς και αυξήσεις', 'Immediate agreement with teachers and raises', 3, -3, 4, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Τα σχολεία ανοίγουν αλλά μεγάλο κόστος.', 'Schools reopen but large cost.'),
(18, 'Ψηφιακή εκπαίδευση και προσωρινές λύσεις', 'Digital education and temporary solutions', 6, -1, 1, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 3, "ΚΚΕ": 2, "ΕΛ": 3}', 'Συνέχεια μαθημάτων αλλά προβλήματα ποιότητας.', 'Continued lessons but quality problems.'),
(18, 'Μεταρρύθμιση εκπαιδευτικού συστήματος', 'Education system reform', 8, -2, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 3, "ΚΚΕ": 1, "ΕΛ": 2}', 'Μακροπρόθεσμα οφέλη αλλά παρατεταμένη κρίση.', 'Long-term benefits but prolonged crisis.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(19, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 5, -4, 3, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(19, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 7, 1, -2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(19, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 6, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(20, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 6, -1, 4, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(20, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 6, 2, -1, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(20, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 5, -1, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(21, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 4, -2, 2, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(21, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 7, 0, -2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(21, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 6, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(22, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 5, -3, 3, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(22, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 6, 1, -1, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(22, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 5, -1, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(23, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 6, -4, 4, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(23, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 7, 2, -2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(23, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 6, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(24, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 4, -1, 2, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(24, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 6, 0, -1, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(24, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 5, -1, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(25, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 5, -2, 3, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(25, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 7, 1, -2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(25, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 6, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(26, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 6, -3, 4, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(26, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 6, 2, -1, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(26, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 5, -1, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(27, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 4, -4, 2, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(27, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 7, 0, -2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(27, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 6, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(28, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 5, -1, 3, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(28, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 6, 1, -1, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(28, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 5, -1, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(29, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 6, -2, 4, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(29, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 7, 2, -2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(29, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 6, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(30, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 4, -3, 2, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(30, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 6, 0, -1, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(30, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 5, -1, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(31, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 5, -4, 3, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(31, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 7, 1, -2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(31, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 6, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(32, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 6, -1, 4, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(32, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 6, 2, -1, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(32, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 5, -1, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(33, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 4, -2, 2, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(33, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 7, 0, -2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(33, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 6, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(34, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 5, -3, 3, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(34, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 6, 1, -1, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(34, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 5, -1, 2, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
INSERT INTO pm_policy_options (scenario_id, option_text, option_text_en, political_cost, economic_impact, social_impact, party_alignment, consequences, consequences_en) VALUES 
(35, 'Κρατική παρέμβαση και άμεση δράση', 'State intervention and immediate action', 6, -4, 4, '{"ΝΔ": 2, "ΣΥΡΙΖΑ": 4, "ΠΑΣΟΚ": 4, "ΚΚΕ": 4, "ΕΛ": 3}', 'Γρήγορη επίλυση με κρατική παρέμβαση αλλά οικονομικό κόστος.', 'Quick resolution with state intervention but economic cost.'),
(35, 'Ιδιωτική πρωτοβουλία και αγορά', 'Private initiative and market forces', 7, 2, -2, '{"ΝΔ": 4, "ΣΥΡΙΖΑ": 2, "ΠΑΣΟΚ": 2, "ΚΚΕ": 1, "ΕΛ": 3}', 'Αποδοτική λύση μέσω αγοράς αλλά κοινωνικό κόστος.', 'Efficient market solution but social cost.'),
(35, 'Συνεργασία και διάλογος', 'Cooperation and dialogue', 6, -2, 3, '{"ΝΔ": 3, "ΣΥΡΙΖΑ": 3, "ΠΑΣΟΚ": 4, "ΚΚΕ": 3, "ΕΛ": 3}', 'Ισορροπημένη προσέγγιση με κοινωνική συναίνεση.', 'Balanced approach with social consensus.');
