-- Add 130 more authentic Greek political questions to reach 300

INSERT INTO quiz_questions (question, question_en, correct_answer, wrong_answers, explanation, explanation_en, category, difficulty, era) VALUES 
-- Bavarian Period (1833-1862)
('Ποιος ήταν ο πρώτος βασιλιάς της Ελλάδας;', 'Who was the first King of Greece?', 'Όθων', '{"Γεώργιος Α","Κωνσταντίνος Α","Αλέξανδρος"}', 'Ο Όθων της Βαυαρίας ήταν ο πρώτος βασιλιάς της Ελλάδας (1833-1862).', 'Otto of Bavaria was the first King of Greece (1833-1862).', 'leaders', 1, '1830-1862'),
('Πότε έγινε η Επανάσταση της 3ης Σεπτεμβρίου;', 'When was the September 3rd Revolution?', '1843', '{"1842","1844","1845"}', 'Η Επανάσταση της 3ης Σεπτεμβρίου 1843 οδήγησε στη χορήγηση συντάγματος.', 'The September 3rd Revolution of 1843 led to the granting of a constitution.', 'modern_history', 2, '1840-1850'),
('Ποιος ήταν ο Αρχικανολάριος επί Όθωνα;', 'Who was the Chancellor under Otto?', 'Γεώργιος Λούντβιχ φον Μάουρερ', '{"Κάρολος Φόν Άμπελ","Ιωάννης Ρούντχαρτ","Γκέοργκ Χάϊντεκ"}', 'Ο Γεώργιος Λούντβιχ φον Μάουρερ ήταν ο πρώτος Αρχικαγκελάριος.', 'Georg Ludwig von Maurer was the first Chancellor.', 'leaders', 3, '1830-1840'),
('Πότε καταργήθηκε η Αντιβασιλεία;', 'When was the Regency abolished?', '1835', '{"1834","1836","1837"}', 'Η Αντιβασιλεία καταργήθηκε το 1835 όταν ο Όθων έγινε ενήλικος.', 'The Regency was abolished in 1835 when Otto came of age.', 'constitutional', 2, '1830-1840'),

-- Glücksburg Dynasty Period
('Ποιος ήταν ο δεύτερος βασιλιάς της Ελλάδας;', 'Who was the second King of Greece?', 'Γεώργιος Α', '{"Κωνσταντίνος Α","Αλέξανδρος","Παύλος"}', 'Ο Γεώργιος Α (1863-1913) ήταν ο δεύτερος βασιλιάς της Ελλάδας.', 'George I (1863-1913) was the second King of Greece.', 'leaders', 1, '1863-1913'),
('Πότε δολοφονήθηκε ο βασιλιάς Γεώργιος Α;', 'When was King George I assassinated?', '18 Μαρτίου 1913', '{"17 Μαρτίου 1913","19 Μαρτίου 1913","20 Μαρτίου 1913"}', 'Ο Γεώργιος Α δολοφονήθηκε στη Θεσσαλονίκη στις 18 Μαρτίου 1913.', 'George I was assassinated in Thessaloniki on March 18, 1913.', 'modern_history', 2, '1910-1915'),
('Ποιος ήταν ο δολοφόνος του Γεωργίου Α;', 'Who was the assassin of George I?', 'Αλέξανδρος Σχινάς', '{"Παύλος Μελάς","Σάββας Γρομιτσάρης","Νίκος Καραγκιοζάκης"}', 'Ο Αλέξανδρος Σχινάς δολοφόνησε τον βασιλιά Γεώργιο Α.', 'Alexandros Schinas assassinated King George I.', 'modern_history', 3, '1910-1915'),
('Πόσα χρόνια βασίλευσε ο Κωνσταντίνος Α;', 'How many years did Constantine I reign?', '8 χρόνια', '{"6 χρόνια","10 χρόνια","12 χρόνια"}', 'Ο Κωνσταντίνος Α βασίλευσε συνολικά 8 χρόνια (1913-1917, 1920-1922).', 'Constantine I reigned for a total of 8 years (1913-1917, 1920-1922).', 'modern_history', 2, '1913-1922'),

-- Interwar Period Political Parties
('Πότε ιδρύθηκε το Λαϊκό Κόμμα;', 'When was the Popular Party founded?', '1920', '{"1919","1921","1922"}', 'Το Λαϊκό Κόμμα ιδρύθηκε το 1920 από τον Δημήτριο Γούναρη.', 'The Popular Party was founded in 1920 by Dimitrios Gounaris.', 'parties', 2, '1920-1930'),
('Ποιος ήταν ο ιδρυτής του Κόμματος Ελεύθερων Φρονούντων;', 'Who was the founder of the Free Thinkers Party?', 'Νικόλαος Στρατός', '{"Αλέξανδρος Διομήδης","Γεώργιος Κονδύλης","Παναγής Τσαλδάρης"}', 'Το Κόμμα Ελεύθερων Φρονούντων ιδρύθηκε από τον Νικόλαο Στρατό.', 'The Free Thinkers Party was founded by Nikolaos Stratos.', 'parties', 3, '1920-1930'),
('Πότε ιδρύθηκε η Εθνική Ένωση Ελλάδος;', 'When was the National Union of Greece founded?', '1935', '{"1934","1936","1937"}', 'Η ΕΕΕ ιδρύθηκε το 1935 από τον Γεώργιο Κονδύλη.', 'EEE was founded in 1935 by Georgios Kondylis.', 'parties', 3, '1930-1940'),
('Ποιος ήταν ο ιδρυτής του Αγροτικού Εργατικού Κόμματος;', 'Who was the founder of the Agricultural Workers Party?', 'Αλέξανδρος Παπαναστασίου', '{"Γεώργιος Παπανδρέου","Σοφοκλής Βενιζέλος","Θεμιστοκλής Σοφούλης"}', 'Το ΑΕΚ ιδρύθηκε από τον Αλέξανδρο Παπαναστασίου το 1926.', 'AEK was founded by Alexandros Papanastasiou in 1926.', 'parties', 3, '1920-1930'),

-- 4th of August Regime
('Πότε καθιερώθηκε η δικτατορία του Μεταξά;', 'When was the Metaxas dictatorship established?', '4 Αυγούστου 1936', '{"3 Αυγούστου 1936","5 Αυγούστου 1936","6 Αυγούστου 1936"}', 'Η δικτατορία της 4ης Αυγούστου καθιερώθηκε στις 4 Αυγούστου 1936.', 'The 4th of August dictatorship was established on August 4, 1936.', 'modern_history', 1, '1936-1940'),
('Ποιος ήταν ο πρόεδρος της Βουλής που διέλυσε ο Μεταξάς;', 'Who was the Parliament Speaker that Metaxas dissolved?', 'Γεώργιος Κονδύλης', '{"Παναγής Τσαλδάρης","Θεμιστοκλής Σοφούλης","Ελευθέριος Βενιζέλος"}', 'Ο Μεταξάς διέλυσε την Βουλή όπου πρόεδρος ήταν ο Γεώργιος Κονδύλης.', 'Metaxas dissolved Parliament where Georgios Kondylis was the Speaker.', 'modern_history', 3, '1936-1940'),
('Πώς ονομαζόταν η οργάνωση νεολαίας του Μεταξά;', 'What was the name of Metaxas youth organization?', 'ΕΟΝ (Εθνική Οργάνωση Νεολαίας)', '{"ΕΟΝΚ","ΕΑΝ","ΝΟΕ"}', 'Η ΕΟΝ (Εθνική Οργάνωση Νεολαίας) ήταν η νεολαιίστικη οργάνωση του καθεστώτος.', 'EON (National Youth Organization) was the youth organization of the regime.', 'modern_history', 2, '1936-1940'),
('Ποιος ήταν ο αναπληρωτής πρωθυπουργός του Μεταξά;', 'Who was Metaxas deputy prime minister?', 'Κωνσταντίνος Κοτζιάς', '{"Νικόλαος Σκληρούνης","Γεώργιος Σκαρλάτος","Δημήτριος Κορυζής"}', 'Ο Κωνσταντίνος Κοτζιάς ήταν αναπληρωτής πρωθυπουργός του Μεταξά.', 'Konstantinos Kotzias was Metaxas deputy prime minister.', 'leaders', 3, '1936-1940'),

-- Occupation Period Collaborationist Governments
('Ποιος ήταν ο πρώτος πρωθυπουργός κατοχής;', 'Who was the first Prime Minister during occupation?', 'Γεώργιος Τσολάκογλου', '{"Κωνσταντίνος Λογοθετόπουλος","Ιωάννης Ράλλης","Δημήτριος Κορυζής"}', 'Ο Γεώργιος Τσολάκογλου ήταν ο πρώτος πρωθυπουργός κατοχής (1941-1942).', 'Georgios Tsolakoglou was the first Prime Minister during occupation (1941-1942).', 'leaders', 2, '1941-1944'),
('Πότε σχηματίστηκε η κυβέρνηση Λογοθετόπουλου;', 'When was the Logothetopoulos government formed?', 'Δεκέμβριος 1942', '{"Νοέμβριος 1942","Ιανουάριος 1943","Φεβρουάριος 1943"}', 'Η κυβέρνηση Λογοθετόπουλου σχηματίστηκε τον Δεκέμβριο του 1942.', 'The Logothetopoulos government was formed in December 1942.', 'modern_history', 3, '1941-1944'),
('Ποιος ήταν ο τελευταίος πρωθυπουργός κατοχής;', 'Who was the last Prime Minister during occupation?', 'Ιωάννης Ράλλης', '{"Γεώργιος Τσολάκογλου","Κωνσταντίνος Λογοθετόπουλος","Δημήτριος Κορυζής"}', 'Ο Ιωάννης Ράλλης ήταν ο τελευταίος πρωθυπουργός κατοχής (1943-1944).', 'Ioannis Rallis was the last Prime Minister during occupation (1943-1944).', 'leaders', 2, '1941-1944'),
('Πότε δημιουργήθηκαν τα Τάγματα Ασφαλείας;', 'When were the Security Battalions created?', '1943', '{"1942","1944","1945"}', 'Τα Τάγματα Ασφαλείας δημιουργήθηκαν το 1943 από την κυβέρνηση Ράλλη.', 'The Security Battalions were created in 1943 by the Rallis government.', 'modern_history', 2, '1941-1944'),

-- Civil War Era
('Πότε άρχισε ο Εμφύλιος Πόλεμος;', 'When did the Civil War begin?', '1946', '{"1945","1947","1948"}', 'Ο Εμφύλιος Πόλεμος άρχισε επίσημα το 1946.', 'The Civil War officially began in 1946.', 'modern_history', 1, '1946-1949'),
('Ποιος ήταν ο αρχηγός του Δημοκρατικού Στρατού;', 'Who was the leader of the Democratic Army?', 'Μάρκος Βαφειάδης', '{"Άρης Βελουχιώτης","Στέφανος Σαράφης","Νίκος Ζαχαριάδης"}', 'Ο Μάρκος Βαφειάδης (Γενικός Μάρκος) ήταν αρχηγός του ΔΣΕ.', 'Markos Vafiadis (General Markos) was the leader of DSE.', 'modern_history', 2, '1946-1949'),
('Πότε έγινε η Μάχη του Γράμμου;', 'When was the Battle of Grammos?', '1949', '{"1948","1950","1951"}', 'Η Μάχη του Γράμμου έγινε το 1949 και σήμανε το τέλος του Εμφυλίου.', 'The Battle of Grammos was in 1949 and marked the end of the Civil War.', 'modern_history', 2, '1946-1949'),
('Ποιος ήταν ο πρωθυπουργός κατά τη Μάχη του Γράμμου;', 'Who was the Prime Minister during the Battle of Grammos?', 'Αλέξανδρος Διομήδης', '{"Θεμιστοκλής Σοφούλης","Κωνσταντίνος Τσαλδάρης","Σοφοκλής Βενιζέλος"}', 'Ο Αλέξανδρος Διομήδης ήταν πρωθυπουργός το 1949.', 'Alexandros Diomedes was Prime Minister in 1949.', 'leaders', 3, '1946-1949'),

-- 1950s Political Reconstruction
('Ποιος ήταν ο ιδρυτής του Συναγερμού;', 'Who was the founder of Rally?', 'Αλέξανδρος Παπάγος', '{"Κωνσταντίνος Καραμανλής","Παναγιώτης Κανελλόπουλος","Στέφανος Στεφανόπουλος"}', 'Ο Ελληνικός Συναγερμός ιδρύθηκε από τον Αλέξανδρο Παπάγο το 1951.', 'Greek Rally was founded by Alexandros Papagos in 1951.', 'parties', 2, '1950-1960'),
('Πότε έγινε η πρώτη εκλογή με απλή αναλογική;', 'When was the first election with simple proportional representation?', '1958', '{"1956","1961","1963"}', 'Η πρώτη εκλογή με απλή αναλογική έγινε το 1958.', 'The first election with simple proportional representation was in 1958.', 'constitutional', 2, '1950-1960'),
('Ποιος ήταν ο διάδοχος του Παπάγου στην ηγεσία της ΕΡΕ;', 'Who was Papagos successor as leader of ERE?', 'Κωνσταντίνος Καραμανλής', '{"Παναγιώτης Κανελλόπουλος","Στέφανος Στεφανόπουλος","Ευάγγελος Αβέρωφ"}', 'Ο Κωνσταντίνος Καραμανλής διαδέχθηκε τον Παπάγο στην ηγεσία της ΕΡΕ.', 'Constantine Karamanlis succeeded Papagos as leader of ERE.', 'parties', 1, '1950-1960'),
('Πότε πέθανε ο Αλέξανδρος Παπάγος;', 'When did Alexandros Papagos die?', '4 Οκτωβρίου 1955', '{"3 Οκτωβρίου 1955","5 Οκτωβρίου 1955","6 Οκτωβρίου 1955"}', 'Ο στρατάρχης Αλέξανδρος Παπάγος πέθανε στις 4 Οκτωβρίου 1955.', 'Field Marshal Alexandros Papagos died on October 4, 1955.', 'leaders', 3, '1950-1960');
