-- Add more authentic questions covering different eras and topics

INSERT INTO quiz_questions (question, question_en, correct_answer, wrong_answers, explanation, explanation_en, category, difficulty, era) VALUES 
-- Leaders Questions
('Ποιος ήταν ο μακροβιότερος πρωθυπουργός της Ελλάδας;', 'Who was the longest-serving Prime Minister of Greece?', 'Ελευθέριος Βενιζέλος', '{"Κωνσταντίνος Καραμανλής","Ανδρέας Παπανδρέου","Κώστας Σημίτης"}', 'Ο Ελευθέριος Βενιζέλος υπηρέτησε συνολικά 12 χρόνια ως πρωθυπουργός.', 'Eleftherios Venizelos served a total of 12 years as Prime Minister.', 'leaders', 2, '1910-1930'),
('Ποιος ήταν ο νεότερος πρωθυπουργός στη νεότερη ιστορία;', 'Who was the youngest Prime Minister in modern history?', 'Αλέξης Τσίπρας', '{"Κυριάκος Μητσοτάκης","Γιώργος Παπανδρέου","Αντώνης Σαμαράς"}', 'Ο Αλέξης Τσίπρας έγινε πρωθυπουργός σε ηλικία 40 ετών το 2015.', 'Alexis Tsipras became Prime Minister at age 40 in 2015.', 'leaders', 1, '2010-2020'),
('Ποιος ήταν ο πρώτος υπουργός Εσωτερικών;', 'Who was the first Interior Minister?', 'Ιωάννης Κολέττης', '{"Σπυρίδων Τρικούπης","Αλέξανδρος Μαυροκορδάτος","Ανδρέας Μιαούλης"}', 'Ο Ιωάννης Κολέττης ήταν ο πρώτος υπουργός Εσωτερικών το 1833.', 'Ioannis Kolettis was the first Interior Minister in 1833.', 'leaders', 3, '1830-1840'),
('Ποια ήταν η πρώτη γυναίκα υπουργός;', 'Who was the first female minister?', 'Λίνα Τσαλδάρη', '{"Ελένη Σκούρα","Μελίνα Μερκούρη","Άννα Μπενάκη-Ψαρούδα"}', 'Η Λίνα Τσαλδάρη ήταν η πρώτη γυναίκα υπουργός (Πρόνοιας) το 1956.', 'Lina Tsaldari was the first female minister (Welfare) in 1956.', 'leaders', 2, '1950-1960'),
('Ποιος ήταν ο τελευταίος πρωθυπουργός πριν τη χούντα;', 'Who was the last Prime Minister before the junta?', 'Παναγιώτης Κανελλόπουλος', '{"Ιωάννης Παρασκευόπουλος","Στέφανος Στεφανόπουλος","Ηλίας Τσιριμώκος"}', 'Ο Παναγιώτης Κανελλόπουλος ήταν πρωθυπουργός όταν έγινε το πραξικόπημα της 21ης Απριλίου.', 'Panagiotis Kanellopoulos was PM when the April 21st coup occurred.', 'leaders', 2, '1960-1970'),

-- More Modern History
('Πότε έγινε η Συνθήκη της Σεβρών;', 'When was the Treaty of Sèvres?', '10 Αυγούστου 1920', '{"12 Αυγούστου 1920","8 Αυγούστου 1920","15 Αυγούστου 1920"}', 'Η Συνθήκη της Σεβρών υπογράφηκε στις 10 Αυγούστου 1920.', 'The Treaty of Sèvres was signed on August 10, 1920.', 'modern_history', 3, '1920-1925'),
('Ποιος ήταν ο αρχηγός των Κομιτατζήδων;', 'Who was the leader of the Komitadjis?', 'Παύλος Μελάς', '{"Τέλλος Άγρας","Γεώργιος Καραβαγγέλης","Ιωάννης Καραβαγγέλης"}', 'Ο Παύλος Μελάς ήταν ένας από τους σημαντικότερους αρχηγούς των Κομιτατζήδων.', 'Pavlos Melas was one of the most important leaders of the Komitadjis.', 'modern_history', 2, '1900-1910'),
('Πότε έγινε η Ένωση της Κρήτης;', 'When was the Union of Crete?', '1913', '{"1912","1914","1915"}', 'Η Κρήτη ενώθηκε επίσημα με την Ελλάδα το 1913.', 'Crete was officially united with Greece in 1913.', 'modern_history', 2, '1910-1915'),
('Ποιος ήταν ο πρώτος Έλληνας στρατηγός;', 'Who was the first Greek general?', 'Θεόδωρος Κολοκοτρώνης', '{"Γεώργιος Καραϊσκάκης","Μάρκος Μπότσαρης","Οδυσσέας Ανδρούτσος"}', 'Ο Θεόδωρος Κολοκοτρώνης θεωρείται ο πρώτος Έλληνας στρατηγός.', 'Theodoros Kolokotronis is considered the first Greek general.', 'modern_history', 1, '1821-1830'),
('Πότε απελευθερώθηκε η Θεσσαλονίκη;', 'When was Thessaloniki liberated?', '26 Οκτωβρίου 1912', '{"25 Οκτωβρίου 1912","27 Οκτωβρίου 1912","28 Οκτωβρίου 1912"}', 'Η Θεσσαλονίκη απελευθερώθηκε στις 26 Οκτωβρίου 1912 κατά τον Α΄ Βαλκανικό Πόλεμο.', 'Thessaloniki was liberated on October 26, 1912 during the First Balkan War.', 'modern_history', 2, '1910-1915'),

-- More Parties Questions
('Πότε ιδρύθηκε το Εθνικό Κόμμα;', 'When was the National Party founded?', '1935', '{"1934","1936","1937"}', 'Το Εθνικό Κόμμα ιδρύθηκε το 1935 από τον Γεώργιο Κονδύλη.', 'The National Party was founded in 1935 by Georgios Kondylis.', 'parties', 3, '1930-1940'),
('Ποιος ήταν ο ιδρυτής του Αγροτικού Κόμματος;', 'Who was the founder of the Agrarian Party?', 'Αλέξανδρος Παπαναστασίου', '{"Γεώργιος Παπανδρέου","Παναγής Τσαλδάρης","Νικόλαος Πλαστήρας"}', 'Το Αγροτικό Κόμμα ιδρύθηκε από τον Αλέξανδρο Παπαναστασίου το 1920.', 'The Agrarian Party was founded by Alexandros Papanastasiou in 1920.', 'parties', 3, '1920-1930'),
('Πότε διαλύθηκε η Ένωση Κέντρου;', 'When was the Center Union dissolved?', '1977', '{"1976","1978","1979"}', 'Η Ένωση Κέντρου διαλύθηκε το 1977 μετά τον θάνατο του Γεωργίου Παπανδρέου.', 'The Center Union was dissolved in 1977 after the death of Georgios Papandreou.', 'parties', 2, '1970-1980'),
('Ποιος ήταν ο ιδρυτής του Εθνικού Συνασπισμού;', 'Who was the founder of the National Coalition?', 'Παναγιώτης Κανελλόπουλος', '{"Ευάγγελος Αβέρωφ","Στέφανος Στεφανόπουλος","Σπύρος Μαρκεζίνης"}', 'Ο Εθνικός Συνασπισμός ιδρύθηκε από τον Παναγιώτη Κανελλόπουλο το 1974.', 'The National Coalition was founded by Panagiotis Kanellopoulos in 1974.', 'parties', 3, '1970-1980'),
('Πότε ιδρύθηκε το ΠΟΛΑΝ;', 'When was POLAN founded?', '1979', '{"1978","1980","1981"}', 'Ο Πολιτικός Ανοιξη (ΠΟΛΑΝ) ιδρύθηκε το 1979 από τον Σπύρο Μαρκεζίνη.', 'Political Spring (POLAN) was founded in 1979 by Spyros Markezinis.', 'parties', 3, '1970-1980');
